project:
  type: website

website:
  title: "Yigit Koray Babal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publication.qmd
        text: Publications

format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 1500px
      margin-width: 300px
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: false



